version: "3.3"
services:
  db:
    image: postgres:14
    container_name: app-db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  api:
    build:
      context: .
    depends_on:
      - db
    container_name: app-api
    env_file:
      - .env
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./:/app/

volumes:
  app-db-data: